apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: essay-project-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: essay.blueandhack.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: essay-project-service
                port:
                  number: 5000
